name: BuildTest
on:
   pull_request:
      branches: [ "dev" ]
   workflow_dispatch:
   
jobs:
   build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.x'

      - name: Install VoiceCraft.Client.Windows WorkLoads
        run: dotnet workload restore ./VoiceCraft.Client/VoiceCraft.Client.Windows/VoiceCraft.Client.Windows.csproj

      - name: Build VoiceCraft.Client.Windows
        run: dotnet build -c Debug ./VoiceCraft.Client/VoiceCraft.Client.Windows/VoiceCraft.Client.Windows.csproj

      - name: Publish VoiceCraft.Client.Windows x64
        run: dotnet publish -c Debug -r win-x64 --self-contained true /p:UseAppHost=true ./VoiceCraft.Client/VoiceCraft.Client.Windows/VoiceCraft.Client.Windows.csproj

      - name: Publish VoiceCraft.Client.Windows x86
        run: dotnet publish -c Debug -r win-x86 --self-contained true /p:UseAppHost=true ./VoiceCraft.Client/VoiceCraft.Client.Windows/VoiceCraft.Client.Windows.csproj

      - name: Zip VoiceCraft.Client.Windows
        run: tar.exe -a -c -f VoiceCraft.Client.Windows.zip ./VoiceCraft.Client/VoiceCraft.Client.Windows/bin/Debug/net9.0-windows

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VoiceCraft.Client.Windows.zip
          path: ./VoiceCraft.Client.Windows.zip
